import React from 'react';

// Os dados do artigo que já existem no arquivo
const articleData = {
  title: "Desvendando a Nova Lei de Apostas no Brasil para 2025: Guia Completo do Apostador",
  introParagraphs: [
    "O mercado de apostas esportivas no Brasil passou por uma transformação significativa nos últimos anos. Antes de 2018, a prática era considerada uma contravenção penal, relegando os entusiastas a plataformas internacionais ou à informalidade. Com a legalização das apostas de quota fixa pela Lei nº 13.756/2018, um novo horizonte se abriu, mas o setor operou por um bom tempo em uma espécie de \"Velho Oeste\", com poucas regras claras e fiscalização incipiente. Esse cenário gerava insegurança para os apostadores e dificultava o desenvolvimento saudável do mercado.",
    "A partir de 2025, essa realidade muda drasticamente com a entrada em vigor da regulamentação completa do setor, um esforço liderado pelo Ministério da Fazenda através da Secretaria de Prêmios e Apostas (SPA-MF). Essa nova fase traz consigo um conjunto de regras rigorosas que visam proteger os apostadores, garantir a integridade das operações, prevenir fraudes e promover o jogo responsável. Para você, apostador, entender essas mudanças é crucial não apenas para se manter em conformidade, mas também para aproveitar ao máximo um ambiente de apostas mais seguro e transparente.",
    "Neste guia completo, o RedeDePalpites vai desvendar todos os detalhes da nova lei de apostas no Brasil. Você encontrará informações claras sobre o que muda no seu dia a dia como apostador, quais são seus novos direitos e deveres, como as casas de apostas (as \"bets\") serão fiscalizadas e, o mais importante, como navegar com segurança e confiança neste novo mercado regulado. Prepare-se para entender desde as novas exigências de cadastro até as medidas de proteção contra o vício em jogos, passando pela importância do domínio \".bet.br\" e muito mais. Vamos juntos explorar essa nova era das apostas esportivas no Brasil!"
  ],
  sections: [
    {
      heading: "Entendendo a Nova Legislação (Lei Nº 14.790/2023)",
      paragraphs: [
        "A Lei nº 14.790, sancionada em dezembro de 2023, representa o marco legal que estrutura de forma definitiva o mercado de apostas de quota fixa no Brasil, incluindo as populares apostas esportivas online. Ela altera e complementa a Lei nº 13.756/2018, que havia dado o primeiro passo para a legalização, mas que carecia de uma regulamentação detalhada para sua plena aplicação, o que só ocorreu com normativos publicados ao longo de 2024 e com plena vigência a partir de 2025.",
        "<strong>Principais objetivos da nova lei:</strong>",
        "A nova legislação surge com propósitos claros e fundamentais para o desenvolvimento saudável e seguro do setor. Entre os principais objetivos, destacam-se:",
        "<ul><li><strong>Proteger os Apostadores:</strong> Criar um ambiente mais seguro, com regras claras sobre identificação, prevenção ao vício e mecanismos de jogo responsável.</li><li><strong>Garantir a Integridade do Esporte:</strong> Implementar medidas para combater a manipulação de resultados e outras fraudes que possam comprometer a lisura das competições.</li><li><strong>Aumentar a Arrecadação Fiscal:</strong> Com a regulamentação, o governo espera formalizar um mercado que já movimenta bilhões e, com isso, aumentar a arrecadação de impostos, que serão destinados a áreas como seguridade social, esporte, turismo e segurança pública.</li><li><strong>Atrair Investimentos:</strong> Oferecer segurança jurídica para que empresas sérias invistam no país, gerando empregos e fomentando a economia.</li><li><strong>Combater a Ilegalidade:</strong> Definir claramente quem pode operar e sob quais condições, facilitando o combate a plataformas ilegais e protegendo os consumidores de operadores mal-intencionados.</li></ul>",
        "<strong>Quem fiscaliza? O papel da Secretaria de Prêmios e Apostas (SPA-MF):</strong>",
        "A responsabilidade primária pela regulamentação, autorização, monitoramento e fiscalização do mercado de apostas de quota fixa no Brasil recai sobre a <strong>Secretaria de Prêmios e Apostas (SPA)</strong>, vinculada ao Ministério da Fazenda. Esta secretaria foi criada especificamente para lidar com as complexidades deste novo mercado.",
        "As atribuições da SPA-MF são amplas e incluem:",
        "<ul><li>Analisar e conceder as licenças de operação para as empresas de apostas.</li><li>Editar portarias e normas complementares para detalhar a aplicação da lei.</li><li>Monitorar as atividades das empresas licenciadas, incluindo o volume de apostas, pagamentos de prêmios e cumprimento das regras de jogo responsável.</li><li>Fiscalizar o cumprimento da legislação, aplicando sanções em caso de irregularidades.</li><li>Manter um canal de comunicação com os apostadores e com o mercado em geral.</li><li>Implementar e gerenciar o sistema de monitoramento centralizado que receberá informações diárias sobre as atividades de apostas.</li></ul>",
        "<strong>O que são apostas de quota fixa?</strong>",
        "Para entender a lei, é essencial saber o que são as \"apostas de quota fixa\", o objeto principal da regulamentação. De forma simples, são aquelas apostas em que o apostador sabe exatamente qual será o fator de multiplicação (a \"odd\" ou \"cotação\") do seu prêmio no momento em que realiza a aposta, caso seu palpite seja vencedor.",
        "Isso significa que, ao apostar em um evento esportivo (como a vitória de um time de futebol), o valor potencial do seu ganho é definido previamente pela casa de apostas e não muda, independentemente do que aconteça depois com o volume de apostas naquele evento ou com as cotações para novos apostadores. Essa previsibilidade é uma característica central das apostas esportivas online mais comuns."
      ]
    },
    {
      heading: "O Que Muda para o Apostador?",
      paragraphs: [
        "A nova regulamentação traz um impacto direto e significativo na experiência do apostador brasileiro. As mudanças visam, acima de tudo, aumentar a segurança, a transparência e promover um ambiente de jogo mais responsável. Vamos detalhar os principais pontos que você, apostador, precisa conhecer:",
        "<h3><strong>Cadastro e Identificação:</strong></h3>",
        "A era dos cadastros simplificados e anônimos chegou ao fim. Para apostar legalmente no Brasil a partir de 2025, a identificação clara do usuário é um requisito fundamental.",
        "<ul><li><strong>Exigência de CPF:</strong> Todas as plataformas autorizadas deverão exigir o Cadastro de Pessoa Física (CPF) no momento do registro. Essa medida visa coibir a participação de menores de idade e facilitar o rastreamento de atividades suspeitas, além de ser um passo importante para o controle fiscal.</li><li><strong>Possível Reconhecimento Facial e Outras Medidas de Segurança:</strong> Além do CPF, a legislação prevê e a SPA-MF pode normatizar a implementação de tecnologias adicionais para verificação de identidade, como o reconhecimento facial. O objetivo é garantir que a pessoa que está se cadastrando é realmente quem diz ser, adicionando uma camada extra de segurança contra fraudes e uso indevido de dados de terceiros.</li><li><strong>Proibição para Menores de 18 Anos (Reforço):</strong> Embora já fosse uma prática comum, a nova lei reforça explicitamente a proibição da participação de menores de 18 anos em qualquer tipo de aposta. As casas de apostas serão rigorosamente fiscalizadas quanto ao cumprimento desta norma, sujeitando-se a pesadas sanções em caso de descumprimento.</li></ul>",
        "<h3><strong>Segurança e Jogo Responsável:</strong></h3>",
        "Um dos pilares da nova regulamentação é a promoção do jogo responsável e a proteção de apostadores vulneráveis. Diversas medidas foram implementadas para mitigar os riscos associados à prática de jogos.",
        "<ul><li><strong>Medidas Contra o Jogo Problemático:</strong> As plataformas licenciadas serão obrigadas a oferecer ferramentas para que os usuários possam gerenciar sua atividade de jogo. Isso inclui a disponibilização de alertas sobre tempo excessivo de jogo ou perdas elevadas, a opção de definir limites de depósito e de apostas, períodos de pausa (auto-limitação temporária) e mecanismos de autoexclusão (onde o próprio usuário pode solicitar o bloqueio de sua conta por um período determinado ou indefinidamente). O objetivo é dar ao apostador mais controle sobre seus hábitos e facilitar a busca por ajuda caso sinta que está perdendo o controle.</li><li><strong>Proibição de Crédito para Apostas:</strong> Fica expressamente proibida a concessão de qualquer tipo de crédito ou adiantamento para que o usuário realize apostas. Isso significa que as casas de apostas não poderão oferecer empréstimos, bônus condicionados a depósitos futuros que funcionem como crédito, ou qualquer outra forma de financiamento para o jogo. O apostador só poderá utilizar recursos que efetivamente possua em sua conta.</li><li><strong>Fim dos Bônus de Entrada (ou Novas Regras para Bônus):</strong> A prática agressiva de oferecer vultosos bônus de boas-vindas apenas para atrair novos cadastros, muitas vezes com regras de rollover complexas e pouco transparentes, está com os dias contados ou será severamente restringida. A regulamentação busca coibir o estímulo excessivo ao jogo, e a SPA-MF detalhará as novas regras para ofertas e bônus, que deverão ser mais claras e menos predatórias. O foco deve ser na qualidade do serviço e na segurança, não em incentivos que possam levar ao endividamento.</li><li><strong>Canais de Atendimento ao Cliente Obrigatórios em Português e no Brasil:</strong> As empresas autorizadas deverão manter canais de atendimento ao cliente eficientes, em língua portuguesa, e com estrutura física ou representantes no Brasil. Isso garante que o apostador tenha a quem recorrer em caso de dúvidas, problemas ou reclamações, facilitando a resolução de conflitos.</li></ul>",
        "<h3><strong>Transparência e Confiabilidade:</strong></h3>",
        "Para aumentar a confiança no sistema, a nova lei impõe maior transparência nas operações das casas de apostas.",
        "<ul><li><strong>Operação Exclusiva em Sites com Domínio \".bet.br\":</strong> Uma das mudanças mais visíveis será a obrigatoriedade de que todos os sites de apostas legalizados no Brasil operem sob o domínio \".bet.br\". Essa medida simples, mas eficaz, permitirá ao apostador identificar rapidamente se uma plataforma é autorizada e regulada pelo governo brasileiro, oferecendo um selo de legalidade e segurança. Desconfie de sites que não utilizem essa terminação a partir de 2025.</li><li><strong>Regras Claras para Pagamento de Prêmios:</strong> As casas de apostas deverão ter regras transparentes e justas para o pagamento dos prêmios, com prazos definidos e sem entraves indevidos. A SPA-MF fiscalizará o cumprimento dessas regras para proteger os direitos dos apostadores ganhadores.</li><li><strong>Proteção de Dados dos Apostadores:</strong> As empresas deverão seguir as diretrizes da Lei Geral de Proteção de Dados (LGPD), garantindo a segurança e a privacidade das informações pessoais e financeiras dos seus usuários.</li></ul>",
        "<h3><strong>Tributação (Impacto no Apostador):</strong></h3>",
        "A questão da tributação dos prêmios é um ponto sensível e que gera muitas dúvidas. A Lei nº 14.790/2023 estabelece que os prêmios líquidos obtidos em apostas de quota fixa serão tributados pelo Imposto de Renda da Pessoa Física (IRPF) à alíquota de 15% sobre o valor que exceder a primeira faixa de isenção da tabela progressiva anual do IRPF (atualmente, R$ 2.259,20 para o ano-calendário de 2024, valor que pode ser atualizado). A retenção será feita na fonte pela própria casa de apostas no momento do pagamento do prêmio. É fundamental que o apostador esteja ciente dessa regra e acompanhe as atualizações da legislação tributária, pois os valores e faixas de isenção podem mudar."
      ]
    },
    {
      heading: "O Que Muda para as Casas de Apostas (Bets)?",
      paragraphs: [
        "A nova legislação impõe uma série de mudanças e obrigações significativas para as empresas que desejam operar no mercado de apostas esportivas no Brasil. O objetivo é profissionalizar o setor, garantir a concorrência leal e proteger os interesses nacionais e dos consumidores.",
        "<h3><strong>Autorização e Licenciamento:</strong></h3>",
        "A principal mudança é a exigência de autorização prévia para operar legalmente no país.",
        "<ul><li><strong>Obrigatoriedade de Autorização da SPA-MF para Operar:</strong> Nenhuma empresa poderá oferecer apostas de quota fixa sem antes obter uma licença da Secretaria de Prêmios e Apostas (SPA-MF). Esse processo de licenciamento será rigoroso e buscará garantir que apenas operadores sérios e financeiramente sólidos atuem no mercado.</li><li><strong>Requisitos para Obtenção da Licença:</strong> Para conseguir a autorização, as empresas deverão cumprir uma série de requisitos, que incluem, mas não se limitam a:<ul><li><strong>Sede e Administração no Brasil:</strong> As empresas deverão ser constituídas segundo as leis brasileiras, com sede e administração no território nacional. Isso facilita a fiscalização e a responsabilização em caso de problemas.</li><li><strong>Comprovação de Capacidade Financeira:</strong> Será exigida a comprovação de capacidade econômico-financeira compatível com o volume de operações pretendido.</li><li><strong>Idoneidade dos Sócios e Dirigentes:</strong> Os sócios e administradores deverão ter reputação ilibada e não poderão ter envolvimento com atividades ilegais.</li><li><strong>Adoção de Políticas de Jogo Responsável:</strong> Apresentação e comprovação da implementação de políticas eficazes de prevenção ao vício e de promoção do jogo seguro.</li><li><strong>Sistemas de Segurança e Prevenção a Fraudes:</strong> Implementação de tecnologias e processos para garantir a segurança das transações e prevenir a lavagem de dinheiro e o financiamento ao terrorismo.</li><li><strong>Pagamento de Taxa de Outorga:</strong> Haverá a cobrança de um valor pela licença de operação, que pode ser considerável, visando selecionar empresas com real interesse e capacidade de investimento no mercado brasileiro.</li></ul></li><li><strong>Consequências para Operadores Não Licenciados:</strong> As empresas que operarem sem a devida autorização da SPA-MF a partir de 2025 serão consideradas ilegais. Suas atividades poderão ser encerradas, seus sites bloqueados e estarão proibidas de realizar qualquer tipo de publicidade ou patrocínio no Brasil. Além disso, seus responsáveis poderão responder criminalmente.</li></ul>",
        "<h3><strong>Obrigações Operacionais:</strong></h3>",
        "Uma vez licenciadas, as casas de apostas terão uma série de obrigações contínuas para manter sua operação regular.",
        "<ul><li><strong>Monitoramento Constante de Transações:</strong> As plataformas deverão monitorar todas as apostas e transações financeiras em tempo real, reportando atividades suspeitas às autoridades competentes.</li><li><strong>Prevenção à Lavagem de Dinheiro e Financiamento ao Terrorismo (PLD/FT):</strong> As empresas deverão implementar programas robustos de PLD/FT, seguindo as diretrizes do COAF (Conselho de Controle de Atividades Financeiras) e da SPA-MF. Isso inclui a identificação rigorosa dos clientes (KYC - Know Your Customer) e o monitoramento de padrões de apostas.</li><li><strong>Implementação de Políticas de Jogo Responsável:</strong> Além das ferramentas oferecidas aos usuários (limites, autoexclusão), as empresas deverão treinar suas equipes para identificar sinais de jogo problemático e oferecer suporte ou encaminhamento para ajuda especializada.</li><li><strong>Sistema de Monitoramento Centralizado pelo Governo:</strong> Todas as operações (apostas, prêmios, depósitos, saques) deverão ser registradas e comunicadas em tempo real a um sistema centralizado de monitoramento controlado pela SPA-MF. Isso permitirá uma fiscalização mais eficaz e a detecção de irregularidades.</li></ul>"
      ]
    },
     {
      heading: "Direitos e Deveres do Apostador",
      paragraphs: [
        "Com a nova regulamentação, os apostadores passam a ter direitos e deveres mais claros. Conhecê-los é fundamental para uma experiência de aposta segura e consciente.",
        "<h3><strong>Direitos do Apostador:</strong></h3>",
        "<ul><li><strong>Acesso a Informações Claras:</strong> Direito de receber informações transparentes sobre as regras dos jogos, as odds, as políticas de pagamento, os termos e condições da plataforma e as medidas de jogo responsável.</li><li><strong>Segurança dos Dados Pessoais:</strong> Direito à proteção de seus dados pessoais e financeiros, conforme a LGPD.</li><li><strong>Recebimento de Prêmios:</strong> Direito de receber os prêmios devidos de forma justa e dentro dos prazos estabelecidos pela casa de apostas, desde que todas as regras tenham sido cumpridas.</li><li><strong>Canais de Suporte Eficientes:</strong> Direito a canais de atendimento ao cliente em português para solucionar dúvidas e problemas.</li><li><strong>Ferramentas de Jogo Responsável:</strong> Direito de acesso a ferramentas de autolimitação, autoexclusão e informações sobre jogo problemático.</li><li><strong>Ambiente de Jogo Íntegro:</strong> Direito de participar de apostas em um ambiente livre de manipulações e fraudes.</li></ul>",
        "<h3><strong>Deveres do Apostador:</strong></h3>",
        "<ul><li><strong>Fornecer Informações Verdadeiras:</strong> Dever de fornecer informações corretas e atualizadas durante o cadastro e sempre que solicitado pela plataforma.</li><li><strong>Não Ser Menor de Idade:</strong> Dever de respeitar a proibição de apostas para menores de 18 anos.</li><li><strong>Jogar de Forma Responsável:</strong> Dever de conhecer seus limites, não apostar mais do que pode perder e buscar ajuda se sentir que o jogo está se tornando um problema.</li><li><strong>Cumprir os Termos e Condições:</strong> Dever de ler e respeitar os termos e condições da casa de apostas.</li><li><strong>Não Participar de Fraudes:</strong> Dever de não se envolver em qualquer tipo de atividade fraudulenta, como conluio, uso de contas de terceiros ou tentativa de manipulação de resultados.</li><li><strong>Declarar Ganhos (quando aplicável):</strong> Dever de estar ciente das obrigações fiscais sobre os prêmios recebidos.</li></ul>"
      ]
    },
    {
      heading: "Dicas para se Adaptar e Apostar com Segurança em 2025",
      paragraphs: [
        "Adaptar-se ao novo cenário regulado exige atenção e algumas práticas recomendadas para garantir uma experiência de aposta positiva e segura:",
        "<ul><li><strong>Escolha Apenas Casas de Apostas Licenciadas (com domínio .bet.br):</strong> Este é o passo mais importante. Verifique sempre se a plataforma possui o domínio oficial \".bet.br\" e se está na lista de operadores autorizados pela SPA-MF (que deverá ser divulgada publicamente). Isso garante que você está lidando com uma empresa que segue as leis brasileiras.</li><li><strong>Leia Atentamente os Termos e Condições:</strong> Antes de se cadastrar e apostar, dedique tempo para entender as regras da casa, especialmente sobre depósitos, saques, bônus e resolução de disputas.</li><li><strong>Utilize as Ferramentas de Jogo Responsável:</strong> Explore e utilize os limites de depósito, de apostas e as opções de autoexclusão oferecidas. Encare as apostas como entretenimento, não como fonte de renda.</li><li><strong>Desconfie de Ofertas Milagrosas:</strong> Odds excessivamente altas ou promessas de ganhos fáceis podem ser sinais de alerta. Opte por plataformas com reputação sólida.</li><li><strong>Mantenha Seus Dados Seguros:</strong> Use senhas fortes, não compartilhe suas informações de login e desconfie de e-mails ou mensagens solicitando dados pessoais em nome da casa de apostas.</li><li><strong>Acompanhe as Notícias do Setor:</strong> Mantenha-se informado sobre novas portarias da SPA-MF e atualizações na legislação. O RedeDePalpites estará aqui para te ajudar com isso!</li><li><strong>Saiba Onde Buscar Ajuda:</strong> Caso sinta que o jogo está se tornando um problema, procure ajuda especializada. Existem diversas organizações que oferecem suporte a jogadores com comportamento aditivo.</li></ul>"
      ]
    },
    {
      heading: "Conclusão",
      paragraphs: [
        "A nova lei de apostas no Brasil, com plena vigência a partir de 2025, marca o início de uma era de maior segurança, transparência e responsabilidade para o setor. Para os apostadores, isso significa um ambiente mais protegido, com regras claras e direitos garantidos. Embora a adaptação possa exigir atenção a novos detalhes, como a identificação rigorosa e o uso exclusivo de plataformas \".bet.br\", os benefícios a longo prazo são inegáveis.",
        "O RedeDePalpites reitera seu compromisso em fornecer informações atualizadas e guias práticos para que você, apostador, possa navegar com confiança neste novo mercado. Lembre-se sempre de priorizar o jogo responsável e de buscar plataformas licenciadas. Boas apostas e conte conosco para se manter sempre bem informado!"
      ]
    },
    {
      heading: "Fontes e Referências",
      paragraphs: [
        "<ul><li>Lei Nº 14.790, de 29 de dezembro de 2023 - Dispõe sobre a modalidade lotérica denominada apostas de quota fixa.</li><li>Lei Nº 13.756, de 12 de dezembro de 2018 - Dispõe sobre o Fundo Nacional de Segurança Pública (FNSP), sobre a destinação do produto da arrecadação das loterias e sobre a promoção comercial e a modalidade lotérica denominada apostas de quota fixa.</li><li>Portarias e normativos da Secretaria de Prêmios e Apostas (SPA) do Ministério da Fazenda (a serem consultados nos canais oficiais do governo).</li><li>Notícias e comunicados oficiais do Ministério da Fazenda sobre a regulamentação das apostas.</li></ul>"
      ]
    }
  ]
};

const NovaLeiApostasPage = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <article className="prose lg:prose-xl max-w-none">
        <h1>{articleData.title}</h1>
        {articleData.introParagraphs.map((paragraph, index) => (
          <p key={`intro-${index}`} dangerouslySetInnerHTML={{ __html: paragraph }} />
        ))}
        {articleData.sections.map((section, sectionIndex) => (
          <section key={`section-${sectionIndex}`} className="mt-6">
            <h2 className="text-2xl font-semibold mb-3">{section.heading}</h2>
            {section.paragraphs.map((paragraph, pIndex) => {
              // Verifica se o parágrafo é uma lista ou subtítulo para não envolvê-lo em <p>
              if (paragraph.trim().startsWith('<ul>') || paragraph.trim().startsWith('<ol>') || paragraph.trim().startsWith('<h3>')) {
                return <div key={`p-${sectionIndex}-${pIndex}`} dangerouslySetInnerHTML={{ __html: paragraph }} className="mb-4"/>;
              }
              return <p key={`p-${sectionIndex}-${pIndex}`} dangerouslySetInnerHTML={{ __html: paragraph }} className="mb-4"/>;
            })}
          </section>
        ))}
      </article>
    </div>
  );
};

export default NovaLeiApostasPage;

